#!/bin/bash
set -e -x

# Add the NodeJS repository for 5.x
# https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
apt-get install -y curl
curl -sL https://deb.nodesource.com/setup_5.x | bash -

# Upgrade the system without prompts
# http://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt
export DEBIAN_FRONTEND=noninteractive
apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade

# Add additional network security parameters, per
# http://blog.mattbrock.co.uk/hardening-the-security-on-ubuntu-server-14-04/
# suggested additions combined with default rules
wget https://raw.githubusercontent.com/JayBeavers/node-git-ec2/master/network-security/10-network-security.conf -O /etc/sysctl.d/10-network-security.conf
service procps start

apt-get install -y fail2ban

# Automatic unattended upgrades, per http://plusbryan.com/my-first-5-minutes-on-a-server-or-essential-security-for-linux-servers
apt-get install -y unattended-upgrades
wget https://raw.githubusercontent.com/JayBeavers/node-git-ec2/master/unattended-upgrades/10periodic -O /etc/apt/apt.conf.d/10periodic

# logwatch settings, per http://blog.mattbrock.co.uk/hardening-the-security-on-ubuntu-server-14-04/
apt-get install -y logwatch
mkdir /var/cache/logwatch
cp /usr/share/logwatch/default.conf/logwatch.conf /etc/logwatch/conf/
rm /etc/cron.daily/00logwatch
wget -O https://raw.githubusercontent.com/JayBeavers/node-git-ec2/master/logwatch/00logwatch -O /etc/cron.weekly/00logwatch

# Enable process accounting, from http://blog.mattbrock.co.uk/hardening-the-security-on-ubuntu-server-14-04/
apt-get install -y acct
wget -O https://raw.githubusercontent.com/JayBeavers/node-git-ec2/master/acct/acct-report -O /etc/cron.weekly/acct-report
touch /var/log/wtmp

# restrict su access, from http://blog.mattbrock.co.uk/hardening-the-security-on-ubuntu-server-14-04/
dpkg-statoverride --update --add root sudo 4750 /bin/su

# Install C++ build tools, git, and NodeJS
apt-get install -y build-essential git-core nodejs

# Route ports 80 and 443 so we don't need to run nodejs as root
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8000
apt-get install iptables-persistent

# Create the git repository for the Application
# Note: this script is running as root, so ~ is not applicable
mkdir /home/ubuntu/app.git
cd /home/ubuntu/app.git
git init --bare

# Create the auto-deploy post-update hook
wget https://raw.githubusercontent.com/JayBeavers/node-git-ec2/master/post-update -O hooks/post-update
chmod 755 hooks/post-update

# Create the app directory to host the nodejs app files
cd /home/ubuntu
git clone file:///home/ubuntu/app.git

# Change ownership from root to ubuntu
chown -R ubuntu:ubuntu app.git
chown -R ubuntu:ubuntu app

# Set up auto-start of website under the ubuntu account
npm install -g upstarter
cd /home/ubuntu/app
upstarter --no-ask -u ubuntu -n nodeapp -d "NodeJS App" -- npm start
